Shader "CookbookShaders/Ch06/GrabPass" 
{
	SubShader
	{
		Tags
		{
			"Queue" = "Transparent"
			"IgnoreProjector" = "True"
			"RenderType" = "Opaque"
		}

		ZWrite On Lighting Off Cull Off Fog{ Mode Off } Blend One Zero

		GrabPass {}	// first pass is a grab pass

		Pass		// rest of the code is in the second pass
		{
			CGPROGRAM

			#pragma vertex vert
			#pragma fragment frag
			#include "UnityCG.cginc"

			sampler2D _GrabTexture;	// automatically generated by the GrabPass

			struct vertInput
			{
				float4 vertex : POSITION;
			};

			struct vertOutput
			{
				float4 vertex : POSITION;
				float4 uvgrab : TEXCOORD1;
			};

			vertOutput vert(vertInput v)
			{
				vertOutput o;
				o.vertex = mul(UNITY_MATRIX_MVP, v.vertex);
				o.uvgrab = ComputeGrabScreenPos(o.vertex);	// grab screen texture
				return o;
			}

			half4 frag(vertOutput i) : COLOR
			{
				fixed4 col = tex2Dproj(_GrabTexture, UNITY_PROJ_COORD(i.uvgrab));	// apply the screen texture in the correct position
				col += half4(0.5, 0, 0, 0);	// add a little red tint just so we can see it
				return col;
			}

			ENDCG
		}
	}
}
